### ISSUE TITLE
[Info/Fix?] Grass deterioration preview

### ISSUE THREAD

**Issue by jexom** [marcrobledo/acnl-editor#3]
Haven't used the editor for a while and noticed the grass map preview. I did some research on how the grass addresses work and made an explanation here: http://imgur.com/a/1DCgq
Tinkering just a bit with the code I managed to get it working correctly for my save file using the MAP_GRASS_PREVIOUS offset and changing width and length from (5,4) to (8,6). I also made the canvas a bit bigger.
Here's what my grass map looks like after the changes: http://i.imgur.com/qCE82Mk.png

**Comment by marcrobledo** [comment]
Very nice, thanks a lot!
Gonna merge it since looks it won't break anything.
I'll take a look at the changes as soon as possible and add a grass editor at last.

**Comment by jexom** [comment]
The only thing I don't really get is your MAP_GRASS_CURRENT offset. Seems to be all 00 for my saves up until MAP_GRASS_PREVIOUS.

**Comment by marcrobledo** [comment]
MAP_GRASS_CURRENT has grass deterioration for the current game session.
The next day at 6:00AM, the game willl substract these values from MAP_GRASS_PREVIOUS next day and grass will deteriorate.

I'm going to close this, since it's not an issue. I'm willing to discuss and help anywhere else :-) Find me at [Twitter](https://twitter.com/marc_robledo)!
