### ISSUE TITLE
Changing town name glitches savegame

### ISSUE THREAD

**Issue by marcrobledo** [marcrobledo/acnl-editor#63]
Seems like changing town name is broken as reported [here](https://gbatemp.net/threads/animal-crossing-new-leaf-save-editor.382965/page-332#post-8614029) and also another source from the Discord server.

However, I've tried to replicate the bug and it works perfectly for me. That piece of code wasn't even changed, so I don't know what is causing the problem.

So I'm going to need more information. Please post your garden.dat or garden_plus.dat files (original and modified glitched ones), post your new desired town name so I can replicate.

Also it would be helpful if you post the web browser you are using too. And also it's very important to know if that was really the only change you did.

**Comment by gardnerk** [comment]
Since you are looking for files, here are a couple I just tried.  In the original file, the town name is Surprise, and the mayor name is Flower.  The only things I changed are the town name (Surprise to Weeding) and the mayor name (Flower to Violet).  In the modified file, the mayor's name was successfully changed, but the town name remained the same on the TPC card and in Isabelle's dialog when opening the game.  I'm using a Mac, and the browser is Safari.  Hope this helps!

Here is the original file (town name Surprise)
[garden_plus.dat.zip](https://github.com/marcrobledo/acnl-editor/files/3132680/garden_plus.dat.zip)

Here is the modified glitched file (town name Weeding)
[garden_plus.dat.zip](https://github.com/marcrobledo/acnl-editor/files/3132682/garden_plus.dat.zip)

**Comment by AzrilAstera** [comment]
I thought you'd like this place better, so upload it here.
There's an original and a modified version in the compressed folder.
I use Windows 10 and Google Chrome.
[Azril_Astera.zip](https://github.com/marcrobledo/acnl-editor/files/3132934/Azril_Astera.zip)

Some Korean users say it is impossible to unlock PwPs one by one.
Sorry, there's no example file for PwPs unlock Not Working.
According to their, it doesn't work to release one by one, but it seems to work to release the whole thing.
They use Windows 10. The browser uses Internet Explorer and Microsoft Edge.

Have a good day!

**Comment by tcd269** [comment]
I'm Mina from the ACHacks Discord. Posting my unmodified garden.dat here for you to look at. I sadly do not have the glitched town file I mentioned in my post. Seems I deleted it as soon as I realized something went wrong.
The town's original name is "Clover". I switched it to "Kamiki" and had issues as soon as I loaded the file. Isabelle welcomes me with my old town name, but the villagers act like they moved from Clover to Kamiki. TPC also shows Clover as the town name.

I use Windows 8 and Google Chrome.

[garden_plus.zip](https://github.com/marcrobledo/acnl-editor/files/3133441/garden_plus.zip)

**Comment by marcrobledo** [comment]
Okay, I'm dumb.

This had been fixed for some reason in my local files. It must had been between 27th April and 28th April, but I can't even remember when I fixed it.

Fix will be commited soon.

**Comment by marcrobledo** [comment]
Should be fixed in 916f432292400bb55b35d985e4eaa0c305bbe31e :-)

You might to force a cache refresh in order to get the latest editor version (make sure it's the 1st May version).

**Comment by marcrobledo** [comment]
I lied.

It's fixed now in 3960fc044a165e44d5c02047a58ca7471d03541f

**Comment by healsl00t** [comment]
saw you wanted things to be on ur github rather than the old forum, just a quick question
on the SE it says i have 10 villagers when only 9 show up in the map and when im actually playing. Had a villager request me to take something to the "10th" villager even though theyre nowhere to be found o.o Did I perhaps do something wrong? Last thing I ever did was box a villager for a friend to pick up. 
Thx xx
