### ISSUE TITLE
Perfect trees flags

### ISSUE THREAD

**Issue by IlCanePerIlGatto** [marcrobledo/acnl-editor#87]
I just wanted to ask what these mean and how they work
![immagine](https://user-images.githubusercontent.com/74318316/172808643-776b510a-ded7-4390-83d4-68934ac6063d.png)
![immagine](https://user-images.githubusercontent.com/74318316/172808661-2c6442f4-a20c-4d66-94de-da8f6a8fb546.png)

Also, could you add flags for dying perfect fruit trees and rotten fruit trees?

**Comment by marcrobledo** [comment]
IIRC, you choose perfect 0/1/4 (it doesn't matter) and the tree becomes perfect fruit tree. Then if you choose mixed, the perfect fruit tree becomes a tree with two normal fruits and a single perfect fruit (just like the tree you've got when you start your town for the first time).

As of the final questions... Sorry, it's been a while since I considered this project finished.
